---

plugins:
  - babel
  - jest

env:
  node: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  no-underscore-dangle: 0
  import/prefer-default-export: 0
